### PR TITLE
Changed to unicode for empty symbol/letter

### PR DESCRIPTION
**Pull request by JockeCK**

### CODE REVIEW

**Comment by nomego** [comment]
@JockeCK Can you provide a screenshot how this looks or a place where it can be tested?

**Comment by JockeCK** [comment]
image

**Comment by JockeCK** [comment]
image

**Comment by nomego** [comment]
Hmm maybe we should also show that symbol in another style, like italic, bold or other color.. to make it more obvious that it's a "special" value.

**Pull request closed without merging**
