### PR TITLE
Adds custom dropdown template slot

### PR DESCRIPTION
**Pull request by JaySunSyn**
I added a `slot` to pass in a custom dropdown template.

### CODE REVIEW

**Comment by nomego** [comment]
Thanks for the contribution! :)
Glad to see you're still into Polymer and our components are getting used elsewhere :)

I don't see a problem with this but haven't tested it. Please test and merge.

**Comment by JaySunSyn** [comment]
Hehe, sure, still Polymer :) But more and more Lit-html..

Thanks for the approval.

**Comment by JaySunSyn** [comment]
Please let me know if I can do something regarding the travis fail. I think that it is unrelated..

**Comment by cristinecula** [comment]
Thanks @JaySunSyn! I'll handle the travis fail.

**Comment by nomego** [comment]
Needs rebase

**Comment by cristinecula** [comment]
@nomego I already rebased this branch, but had to submit as a different PR: https://github.com/Neovici/paper-autocomplete-chips/pull/45

**Comment by nomego** [comment]
Ah sorry missed it! Closed by #45

**Pull request closed without merging**
